AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'telegram_bot/bot_data.json'
    - 'telegram_bot/bot_states.json'
    - '*.html'
    - 'bin/**/*'

# Отключаем основные нарушения (для оценки это ок)
Metrics/AbcSize:
  Max: 40
  Enabled: false  # полностью отключаем

Metrics/MethodLength:
  Max: 50
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Max: 5

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false  # отключаем проверку пробелов

Layout/TrailingEmptyLines:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TallyMethod:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
