# Gemfile
source 'https://rubygems.org'

gem 'telegram-bot-ruby', '~> 0.19.2'
gem 'faraday', '~> 2.7'
gem 'json', '~> 2.6'

group :development do
  gem 'pry', '~> 0.14.0'
  gem 'rubocop', '~> 1.50', require: false
end
